apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: argocd-redirect-to-https
  namespace: argocd
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # 🔗 Humne purani 'serversscheme: https' wali line hata di hai
    traefik.ingress.kubernetes.io/router.middlewares: argocd-argocd-redirect-to-https@kubernetescrd
spec:
  tls:
  - hosts:
    - argo-farhan.duckdns.org
    secretName: argocd-server-tls-secret
  rules:
  - host: argo-farhan.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80 # 🌟 FIX: Port 443 ki jagah 80 kar diya hai