apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio-deployment
  labels:
    app: my-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec: #  Sahi hai! Ab isme 4 spaces hain, ye 'template' ke andar aa gaya hai
      containers:
      - name: react-app
        image: farhan091/my-portfolio:204cbe28f78c06445e980305801b67e6943c5d31
        ports:
        - containerPort: 80
        imagePullPolicy: Always